version: "3.8"

services:
  ovpn-as:
    build:
      context: .
      dockerfile: Dockerfile
    image: ovpn-as:ubuntu20.04-x86
    container_name: ovpn-as
    ports:
      - "1443:443"
      - "943:943"
      - "1194:1194/udp"
    privileged: true
